spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /huang
    username: huangkaiwen
    password: 744669
    listener:
      direct:
        prefetch: 1 #每次只能获取一条消息，处理完才能获取下一条
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: true # true无状态，false有状态，如果业务中包含事务则改为false
